  name: On push to any branch

  on:
    pull_request:
      branches: [ '**' ]

  jobs:
    call-build-workflow:
      uses: ./.github/workflows/maven-build.yml
    call-veracode-workflow:
      uses: ./.github/workflows/veracode-scan.yml
      needs: call-build-workflow
      secrets: inherit
    call-veracode-upload-and-scan-workflow:
      uses: ./.github/workflows/veracode-upload-and-scan.yml
      needs: call-build-workflow
      secrets: inherit
