name: On push to main

on:
  push:
    branches:
      - main

jobs:
#   call-build-workflow:
#     uses: ./.github/workflows/maven-build.yml
#   call-codeql-workflow:
#     uses: ./.github/workflows/codeql.yml  
#   call-veracode-workflow:
#     uses: ./.github/workflows/veracode-scan.yml
#     needs: call-build-workflow
#     secrets: inherit
    call-veracode-agent-scan-workflow:
      uses: ./.github/workflows/veracode-agent-scan.yml
      secrets: inherit

