  name: On PR to main

  on:
    pull_request:
      branches:
        - main

  jobs:
    call-build-workflow:
      uses: ./.github/workflows/maven-build.yml
    call-veracode-workflow:
      needs: call-build-workflow
      uses: ./.github/workflows/veracode-scan.yml 
    call-veracode-upload-and-scan-workflow:
      uses: ./.github/workflows/veracode-upload-and-scan.yml
      needs: call-build-workflow
      secrets: inherit
