name: Veracode SCA Scan

on:
  workflow_call:
  
jobs:

  veracode-agent-scan:
    runs-on: ubuntu-latest
    name: Veracode SCA Agent Scan

    steps:
        # Get the compiled binary from a previous job
      - name: Download and Unzip the Pipeline Scanner
        run: curl -sSL https://www.sourceclear.com/install | sh
        
      - name: Checkout 
        uses: actions/checkout@v3
          
      - name: Set the SCA Token
        run: |
          export SRCCLR_API_TOKEN=${{ secrets.SCA_TOKEN }}  
          ls -a
          srcclr scan
        
      - name: Scan by URL
        run: echo "${{ github.GITHUB_SERVER_URL }} / ${{ github.GITHUB_REPOSITORY }}
          
          
